### ISSUE TITLE
Postgres 11 support

### ISSUE THREAD

**Issue by mgoldshteyn** [EnterpriseDB/mysql_fdw#169]
I am using PG 11 Beta 2. Does the MySQL FDW work with PG 11?

**Comment by ChristophBerg** [comment]
At the moment it does not:
```
postgresql-mysql-fdw/Makefile:52: *** PostgreSQL 9.3, 9.4, 9.5, 9.6 or 10beta is required to compile this extension.
```
Is this extension still maintained? It seems pretty neglected.

**Comment by robertmhaas** [comment]
This issue was just resolved by mithuncy.

**Comment by slava-pagerduty** [comment]
it still installs under /usr/share/postgresql/10/ even though I have pg 11. I don't have postgres 10.
using ubuntu 18.04

**Comment by ChristophBerg** [comment]
@slava-pagerduty: if you are compiling from source, you need PG11's `pg_config`. Run `pg_config` to check. Otherwise, install the package for PG11, `postgresql-11-mysql-fdw` on Debian.
