### ISSUE TITLE
Dropped Connection

### ISSUE THREAD

**Issue by ssmoss** [EnterpriseDB/mysql_fdw#18]
I am getting the following error:

```
# explain select id from fdw_mysql_table limit 10;
ERROR:  failed to execute the MySQL query: 
MySQL server has gone away
```

Until I restart my postgres session I cannot preform any more queries.

**Comment by ahsanhadi** [comment]
As explained by Ibrar in previous post on this ticket, we have addressed two main issues from the list, the 3rd is not something we can fix in the FDW code. I am closing this, please let me know if this needs to be reopened.
