### ISSUE TITLE
fetch size option?

### ISSUE THREAD

**Issue by jackrabbithanna** [EnterpriseDB/mysql_fdw#192]
I'm trying to use mysql_fdw to connect to a MySQL View, which has a complex query and could have over 1 million results. 

If I query against the View in MySQL .. I get query speeds in like a few seconds, but the same query in the FDW is many minutes :(

I was wondering if the server option 'fetch size' as or will be implemented sometime soon.

Thanks!

**Comment by Kazmirchuk** [comment]
+1 this would be very relevant for my project as well. What is the current default fetch size?

**Comment by jeevanladhe** [comment]
Hi,

Current fetch size is 100, and currently it is not configurable. Thanks for
showing interest in this, we can add this in our TODO list and will try to
implement this in future releases depending on other priorities.

Regards,
Jeevan Ladhe

**Comment by surajkharage19** [comment]
Hi,

With the recent commit ee131775b71bae9060daf9b690fe44c7aa61b263, we can set fetch_size at per-table or per-server level in mysql_fdw. Can you please check if that serves the purpose at your end?

**Comment by surajkharage19** [comment]
Hi @jackrabbithanna and @Kazmirchuk,

We have not received further updates from you on this. Hoping that issue is resolved.
We are closing the case for now. If the issue persists, you can reopen the case anytime.
