### ISSUE TITLE
ERRORDATA_STACK_SIZE exceeded

### ISSUE THREAD

**Issue by man1100** [EnterpriseDB/mysql_fdw#210]
Hi guys,

I found the following behaviour, using mysql_fdw (2.5.4-2.pgdg90) and a PG 11 instance (11.9-1.pgdg90) importing from a mariadbdb (10.4.12) instance to initialize foreign tables

- PANIC:  ERRORDATA_STACK_SIZE exceeded 
- crash of the postgresql instance

The max_stack_depth is high (128Mb), but any change of this parameter have
no effect, it fails at the #5 try of the following comand:

api=# DROP FOREIGN TABLE IF EXISTS import_zzz.zzz_contact_event_prod;IMPORT
FOREIGN SCHEMA "schema_V3" limit to ( "zzz_contact__prod") FROM SERVER
mysql_zzz INTO import_zzz;
DROP FOREIGN TABLE
IMPORT FOREIGN SCHEMA

No problem during the four first executions in the same connexion (sql file played)
and fails at the fifth's

DROP FOREIGN TABLE
PANIC:  ERRORDATA_STACK_SIZE exceeded
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.

Any help will be quite appreciated,

Thanks
Emmanuel

**Comment by vaibhavdalvi93** [comment]
Thank you @man1100 for reporting an issue.

I am able to reproduce the above issue.
We are internally tracking this and will try to address this issue as soon as possible.

**Comment by surajkharage19** [comment]
Hi,

We have fixed the above-mentioned issue. Please check at your end.
We are closing the case for now. If the issue persists, you can reopen the case anytime.
