### ISSUE TITLE
for windows

### ISSUE THREAD

**Issue by skr2538** [EnterpriseDB/mysql_fdw#211]
what are the steps for this in windows?

**Comment by surajkharage19** [comment]
Hi @skr2538,

Currently, we don't support mysql_fdw on windows.

Below is the list of supported platforms, you can use any of them:

Linux x86-64
• RHEL 8.x/7.x
• CentOS 8.x/7.x
• OEL 8.x/7.x
• Ubuntu 20.04/18.04 LTS
• Debian 10.x/9.x
Linux on IBM Power8/9 (LE)
• RHEL 7.x

**Comment by surajkharage19** [comment]
Hi,

As stated above, you can try mysql_fdw on the supported platform and we would be happy to provide you support. 
We are closing the case for now. If the issue persists on the supported platform, you can reopen the case anytime.
