### ISSUE TITLE
Foreign schema is not present on foreign server

### ISSUE THREAD

**Issue by mrendi29** [EnterpriseDB/mysql_fdw#214]
The mysql_fdw is not importing certain foreign schemas despite the schema existing on the foreign MySQL server.  I have tried other schemas and they import fine  

I get the following error:
ERROR:  schema "foreign_schema" is not present on foreign server "foreign_server"

I traced the source code to here:
https://github.com/EnterpriseDB/mysql_fdw/blob/master/mysql_fdw.c#L2033

**Comment by surajkharage19** [comment]
Thanks @mrendi29 for reporting this.
Can you please share the small reproducible test case where you are unable to import schema and getting an error?
It would be good if you provide schema/database DDL from MySQL along with IMPORT FOREIGN SCHEMA command.
The error is expected when the schema/database does not exist on MySQL side.

**Comment by mrendi29** [comment]
@surajkharage19 I was able to fix the issue this morning. I had to use double quotes around the tables i was specifying in the LIMIT TO statement
