### ISSUE TITLE
what is the process to install in windows server

### ISSUE THREAD

**Issue by brozenjon** [EnterpriseDB/mysql_fdw#216]
I have been trying this but I can't find how it can be installed in windows server. I am running postgres 12

**Comment by surajkharage19** [comment]
Hi @brozenjon, 

Currently, mysql_fdw is not supported on the Windows server. Below are the supported versions:

The MySQL Foreign Data Wrapper is supported for MySQL 8 on the following platforms: 
RHEL 8.x/7.x
CentOS 8.x/7.x
OEL 8.x/7.x
Ubuntu 20.04/18.04 LTS 
Debian 10.x/9.x

The MySQL Foreign Data Wrapper is supported for MySQL 5 on the following platforms: 
RHEL 7.x
CentOS 7.x
OEL 7.x
Ubuntu 18.04 LTS 
Debian 10.x/9.x
Linux on IBM Power8/9 (LE) RHEL 7.x

Thanks,
Suraj Kharage

**Comment by brozenjon** [comment]
thanks for promp answer
