### ISSUE TITLE
Postgresql support for push down  "order by N limit M"

### ISSUE THREAD

**Issue by MondayLiu** [EnterpriseDB/mysql_fdw#217]
select * from forign_table 
where date between 20210101 and 20210525 
order by date desc 
limit 100;

If don't  support "order by n limit m" push down,  A large number of records will retrieved from MySQL.

**Comment by surajkharage19** [comment]
Hi @MondayLiu,

Currently, mysql_fdw does not support ORDER BY and LIMIT/OFFSET pushdown. This is on our roadmap and we will try to implement that in the future but not immediately.

**Comment by MondayLiu** [comment]
Hi  @surajkharage19 ,
Thank you for response! 
About when will this feature be available？

**Comment by surajkharage19** [comment]
Hi @MondayLiu,

This feature is on our roadmap but we don't have an exact timeline when that feature will be available.

**Comment by davidkumru** [comment]
Hi @surajkharage19, could you provide us an update on the status of adding additional clauses like `LIMIT` and `ORDER BY`?

**Comment by surajkharage19** [comment]
Hi,

We have now committed ORDER BY and LIMIT OFFSET pushdown in mysql_fdw under commits d42f06c6182de8f00298c4c453ee9ea231abdc26 , 44d963146a9fd93441cfbe961d96f4a38c6233cf respectively.  Please check if that is useful at your end and share the feedback.

**Comment by surajkharage19** [comment]
Hi @MondayLiu,

We have not received further updates from you on this. Hoping that issue is resolved at your end.
We are closing the case for now. If the issue persists, you can reopen the case anytime.
