### ISSUE TITLE
(Fixed) After a successful PG upgrade, it failed to connect to mysql databases that it can connect. 

### ISSUE THREAD

**Issue by eugeneYWang** [EnterpriseDB/mysql_fdw#223]
Upgraded PG 9.6 to PG 12 on the same VM using pg_upgrade, so the foreign data wrapper's db info and user mappings were moved to the new PG 12 too. When I try to use mysql_fdw to create a foreign table in the new PG 12 DB, It told me that 

```
ERROR:  failed to connect to MySQL: Unknown MySQL server host '' (-2)
CONTEXT:  SQL statement "import foreign schema etl_data
	limit to (md_loc_delta_ps)
    from SERVER c2f_prod
    into fd_mysql"
PL/pgSQL function eugene.increment_sync_md_location() line 7 at SQL statement
SQL state: HV00N
```
The above message is copied from pgAdmin4. 
Before the PG upgrade, we can read this table. In server c2f_prod, we have host value and port value specified. 

```
CREATE SERVER c2f_prod
    FOREIGN DATA WRAPPER mysql_fdw
    OPTIONS (host '192.168.xx.xx', port '3306');
 ```
 
 Not sure why error message indicate `''` as unknown mysql server host.

**Comment by eugeneYWang** [comment]
Tried to delete and recreate the extension and server mappings and user mappings. It still do not work.

**Comment by eugeneYWang** [comment]
I just got it solved.... so here is the solution:

in our case, we actually also upgraded the ubuntu version from 16.04 to 20.04 but postgresql-12-mysql-fdw is installed before OS upgrade. 

So even mysql_fdw is the same version(2.5.5), the OS version of this library is 16.04. 

Eventually, what I did to solve the issue is : 

add postgres repository to as apt sources first , then install the library again ( actually system info prompt me this is an upgrade)
```
sudo apt-get install  postgresql-12-mysql-fdw
```

Then just restart the database.

**Comment by eugeneYWang** [comment]
Before I tried this solution, I recreated mysql_fdw extension. It helps to make sure the mysql_fdw sql 1.1 file is applied, otherwise it was 1.0 (strange, because before PG upgrade I have applied the sql 1.1 upgrade) 

not sure if this is relevant to the solution.

**Comment by luss** [comment]
Personally, for this kinda upgrade I'd recommend upgrading your pg96
instance to the latest version of MySQL FDW as step one.

1.) Creating (& testing) a new Ubuntu 20.04 VM w/ exisitng versions of pg96
and mysqlfdw as step one.

2.) upgrade to latest mysqlfdw on pg96 on new instance of Ubu20 and testing
that it is ok

5.) upgrade to pg12 (or eben pg13) on new instance of Ubu20

Practice it once or twice and then it will go smoothly on switchover day.

--Luss
