### ISSUE TITLE
Could not create the mysql_fdw extension in postgres in centos 8.

### ISSUE THREAD

**Issue by surajmachamasi** [EnterpriseDB/mysql_fdw#236]
getting this issue, when creating the mysql_fdw extension. 

```
ERROR:  could not open extension control file "/usr/pgsql-12/share/extension/mysql_fdw.control": No such file or directory
dbs=# 
dbs=# 
dbs=# create extension mysql_fdw;
ERROR:  could not open extension control file "/usr/pgsql-12/share/extension/mysql_fdw.control": No such file or directory

```
mysql_fdw does exists on that location.

![image](https://user-images.githubusercontent.com/84307751/154713374-4c7e984e-a882-41eb-b9aa-036f9f47fa8f.png)

SO file status 
![image](https://user-images.githubusercontent.com/84307751/154713469-107c2229-442a-4c10-99bf-3d37a4c7d8fa.png)

**Comment by surajkharage19** [comment]
Hi,

From the details, it is not clear the location of mysql_fdw.control file. Can you please make sure that mysql_fdw.control file exists at location "/usr/pgsql-12/share/extension/" with proper permissions. Also, it would be good if you could share the exact steps followed at your end to setup mysql_fdw.

**Comment by surajmachamasi** [comment]
yes it does exists in that location.

**Comment by surajmachamasi** [comment]
![image](https://user-images.githubusercontent.com/84307751/154918537-ba5d9e99-6129-416c-96ce-53c351f4daf7.png)

**Comment by surajmachamasi** [comment]
i copied the mysql_fdw.so file and mysql_fdw.control and mysql_fdw--1.1.sql file to required location and created the docker image.

**Comment by surajkharage19** [comment]
Can you please try installing mysql_fdw using source code or RPM and check if you are still getting the same issue? The steps for source code installation are mentioned in below link:
https://github.com/EnterpriseDB/mysql_fdw

**Comment by surajkharage19** [comment]
Hi @surajmachamasi,

Are you still facing this issue at your end? We can help you if the issue is still there.
If not then can you please close the case from your end?
