### ISSUE TITLE
Error decode utf-8 after upgrade

### ISSUE THREAD

**Issue by guenlm** [EnterpriseDB/mysql_fdw#255]
Hi

I did an update on my ubuntu 20.04.4 yestarday with the latest version of mysql-fdw (postgresql-14-mysql-fdw_2.8.0-1.pgdg20.04+1) and now, I have this error on all my wrapper :
'utf-8' codec can't decode byte 0xe9 in position 61: invalid continuation byte
Can you help me please (the server is in prod...)
thank's

guen

**Comment by surajkharage19** [comment]
Hi @guenlm,

Thanks for reporting an issue.
Can you please share the complete reproducible test case with all details as I am not able to understand your concern fully?

**Comment by guenlm** [comment]
ok.
Ubuntu Linux 20.04.4
pgAdmin 6.9
postgresql-14-mysql-fdw:amd64 2.8.0-1.pgdg20.04+1 (since yesterday...since the problem....)

I have a test mysql_fdw like this
```
CREATE FOREIGN TABLE IF NOT EXISTS mysql_master.tabtest(
    id integer NOT NULL,
    text character varying(255) NULL COLLATE pg_catalog."default"
)
    SERVER mysql_server
    OPTIONS (dbname 'trace_master', table_name 'tabtest');
```

The table tabtest on Mysql'server is in utf-8.
When I put a special character in text (like 'guena**ë**l' for example), I have an error on pgadmin like this :
'utf-8' codec can't decode byte 0xe9 in position 61: invalid continuation byte
I have too an error of character inrecognize in qgis which use this fdw (so it's not only a problem with pgadmin)
All was good before the last update (and restart of the server) yesterday evening.
Thank's

**Comment by guenlm** [comment]
sorry but how can I do that (a persistant way...) ?
thank's

**Comment by guenlm** [comment]
ok I found and it work's. I add an option on my mysql_fdw with character_set=PGDatabaseEncoding
thank's a lot !
