### ISSUE TITLE
question , about join

### ISSUE THREAD

**Issue by cooltnt** [EnterpriseDB/mysql_fdw#259]
Want to ask for advice.

Whether it is possible to directly join the table when creating an foreign table, not create two foreign table first   then join

**Comment by surajkharage19** [comment]
Hi @cooltnt,

We don't have such functionality, you need to create foreign tables separately to join.

**Comment by cooltnt** [comment]
> Hi @cooltnt,
> 
> We don't have such functionality, you need to create foreign tables separately to join.

ok ,  but I think if can use query when create foreign table, that would be great.  

Because many times I just want the results of multiple table joins.

And I found that I could not get the view in MySQL,  Is this operation not supported ?

**Comment by surajkharage19** [comment]
Hi @cooltnt,

> ok , but I think if can use query when create foreign table, that would be great.
Currently, this is not on our roadmap and it seems we don't have infrastructure for the same.

> And I found that I could not get the view in MySQL, Is this operation not supported ?
You can create a foreign table on the remote MySQL view. You can perform select operations on a foreign table but can NOT do insert/update/delete because of the unique column requirement.

Hope this helps.

**Comment by cooltnt** [comment]
> Hi @cooltnt,
> 
> > ok , but I think if can use query when create foreign table, that would be great.
> 
> Currently, this is not on our roadmap and it seems we don't have infrastructure for the same.
> 
> > And I found that I could not get the view in MySQL, Is this operation not supported ?
> 
> You can create a foreign table on the remote MySQL view. You can perform select operations on a foreign table but can NOT do insert/update/delete because of the unique column requirement.
> 
> Hope this helps.

Hi @surajkharage19 ,

I tried to create a view on remote MySQL, but an error occurred when select the foreign table ( The view in MySQL is normal ) 

"ERROR: failed to prepare the MySQL query:  Table 'f_eosbdata.v_zt_ksxxh_old' doesn't exist"

create sql : 
CREATE FOREIGN TABLE public.v_zt_ksxxh_old_mysql_fdw_test(
	KMMC text NULL, KSMC text NULL, KSFL text NULL
)
SERVER mysql_server_test OPTIONS (dbname 'f_eosbdata', table_name 'v_zt_ksxxh_old');

**Comment by cooltnt** [comment]
Hi @surajkharage19 

I made a very stupid mistake, now it is working fine.  

Thank you very much for your attention.
