### ISSUE TITLE
avoid confusion with dpage mysql_fdw

### ISSUE THREAD

**Issue by eMerzh** [EnterpriseDB/mysql_fdw#26]
When you grab mysql_fdw from pgxn you get an old version from dpage.
the version reported by pg is 1.0 ... same as the version here...

it might be a good idea to upgrade version or change name  or smth  to be able to distinguish them ...
and to update pgxn.org with the related info to avoid any confusion

Thanks

**Comment by eMerzh** [comment]
@ahsanhadi @dpage any news on this? i've heard other people facing the same issue

**Comment by ahsanhadi** [comment]
Ibrar should be able update this, he has co-ownership for mysql fdw on PGXN.

Ibrar,
Can you please take care of this...

On Tue, Feb 3, 2015 at 2:05 AM, eMerzh <notifications@github.com> wrote:

> @ahsanhadi <https://github.com/ahsanhadi> @dpage
> <https://github.com/dpage> any news on this? i've heard other people
> facing the same issue
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EnterpriseDB/mysql_fdw/issues/26#issuecomment-72537570>
> .
>



-- 
Ahsan Hadi
Snr Director Product Development
EnterpriseDB Corporation
The Enterprise Postgres Company

Phone: +92-51-8358874
Mobile: +92-333-5162114

Website: www.enterprisedb.com
EnterpriseDB Blog: http://blogs.enterprisedb.com/
Follow us on Twitter: http://www.twitter.com/enterprisedb

This e-mail message (and any attachment) is intended for the use of the
individual or entity to whom it is addressed. This message contains
information from EnterpriseDB Corporation that may be privileged,
confidential, or exempt from disclosure under applicable law. If you are
not the intended recipient or authorized to receive this for the intended
recipient, any use, dissemination, distribution, retention, archiving, or
copying of this communication is strictly prohibited. If you have received
this e-mail in error, please notify the sender immediately by reply e-mail
and delete this message.

**Comment by eMerzh** [comment]
Thanks guys \o/
