### ISSUE TITLE
Mysql_fdw on windows?

### ISSUE THREAD

**Issue by 564songil** [EnterpriseDB/mysql_fdw#267]
hello, I am trying to install mysql_fdw in windows os but it is very difficult since I haven't used linux before is it possible for a winodows installation guidance?

**Comment by surajkharage19** [comment]
Hi,

Currently, we do not support the Windows platform and hence we do not have the instructions for windows listed anywhere.

**Comment by 564songil** [comment]
thank you for the fast reply!
