### ISSUE TITLE
Postgres 16 support

### ISSUE THREAD

**Issue by Deltaus** [EnterpriseDB/mysql_fdw#277]
Hi there, so postgres beta 1 has been out and beta 2 was stamped earlier this week, may I know when we can expect a PG 16 compatible version to be released? Thank you!

**Comment by surajkharage19** [comment]
Hi @Deltaus,

We are working on this and soon PG 16 compatible version to be released.

**Comment by surajkharage19** [comment]
Hi @Deltaus,

We have now added the Postgres 16 support. You can pull the latest sources and try it out.
Please let us know if you face any further issues on this.

**Comment by Deltaus** [comment]
Confirmed. Built successfully, thank you!
