### ISSUE TITLE
How to increase wait_timeout and interactive_timeout on mysql_fdw?

### ISSUE THREAD

**Issue by gferrette** [EnterpriseDB/mysql_fdw#278]
Hello!

Please, how do I increase wait_timeout and interactive_timeout in mysql_fdw?

Thanks in advance!

**Comment by gferrette** [comment]
Hello!

It works! Thank you very much!

**Comment by surajkharage19** [comment]
Glad to hear that your issue is resolved. Please let me know if you have further queries on this. If not, then can you please close this case?

**Comment by gferrette** [comment]
Sure!

Thanks!!
