### ISSUE TITLE
Cannot create foreign table based on a view

### ISSUE THREAD

**Issue by kreynolds** [EnterpriseDB/mysql_fdw#28]
```
ERROR:  failed to execute the MySQL query: 
EXPLAIN/SHOW can not be issued; lacking privileges for underlying table
```

There are no underlying permissions issues, I can select from the view using the normal mysql client.

**Comment by adamonduty** [comment]
I ran into the same issue, which can be solved by GRANT'ing the SHOW VIEW capability in mysql:

```
GRANT SHOW VIEW ON `mydatabase`.* TO 'myuser'@'%';
```

Having the SELECT capability alone is not enough. There is a bit more background <a href="http://bugs.mysql.com/bug.php?id=64198">here</a>.
