### ISSUE TITLE
Build fails with mariadb on Debian

### ISSUE THREAD

**Issue by Kazmirchuk** [EnterpriseDB/mysql_fdw#309]
The Makefile doesn't work when I need to link against mariadb on Debian 12 (probably applies to Ubuntu as well)
E.g. take [this](https://hub.docker.com/r/bitnami/postgresql) base image, then
```
apt update && apt install -y --no-install-recommends libmariadb-dev gcc make
```
The Makefile needs the following adjustments to work:
1. Use mariadb_config instead of mysql_config
2. findstring mariadb (no "client")
3. MYSQL_LIB = mariadb
4. _MYSQL_LIBNAME=\"lib$(MYSQL_LIB)$(DLSUFFIX).3\" (note the .3 in the end)

**Comment by surajkharage19** [comment]
Hi @Kazmirchuk,

Officially, we do not support Mariadb for mysql_fdw. If these changes are working at your end then you can commit locally and continue using the same. Alternatively, we are planning to release Debian 12 packages for both PG and EPAS, so if that fits for you then you can start using the same once released.

**Comment by Kazmirchuk** [comment]
thanks for clarifying. Prebuilt packages for Debian will be appreciated.
