### ISSUE TITLE
query with a function doesn't work

### ISSUE THREAD

**Issue by zdenda145** [EnterpriseDB/mysql_fdw#42]
I have this query:
`SELECT * FROM some_foreign_table WHERE date(datetime_column)='2013-08-30';`
and after sent I get this error:
`ERROR: failed to prepare the MySQL query:
FUNCTION db.date does not exist `

**Comment by ahsanhadi** [comment]
On Fri, Feb 27, 2015 at 2:34 PM, zdenda145 <notifications@github.com> wrote:

> I have this query:
> SELECT * FROM some_foreign_table WHERE date(datetime_column)='2013-08-30';
> and after sent I get this error:
> ERROR: failed to prepare the MySQL query:
> FUNCTION db.date does not exist
>
> —
>
I believe functions used in the where clause need to be present in both PG
and mysql in order for them to be used and pushed down. In the case above
date is a mysql function and not present in PG.

Ibrar, can you confirm this please...


> Reply to this email directly or view it on GitHub
> <https://github.com/EnterpriseDB/mysql_fdw/issues/42>.
>



-- 
Ahsan Hadi
Snr Director Product Development
EnterpriseDB Corporation
The Enterprise Postgres Company

Phone: +92-51-8358874
Mobile: +92-333-5162114

Website: www.enterprisedb.com
EnterpriseDB Blog: http://blogs.enterprisedb.com/
Follow us on Twitter: http://www.twitter.com/enterprisedb

This e-mail message (and any attachment) is intended for the use of the
individual or entity to whom it is addressed. This message contains
information from EnterpriseDB Corporation that may be privileged,
confidential, or exempt from disclosure under applicable law. If you are
not the intended recipient or authorized to receive this for the intended
recipient, any use, dissemination, distribution, retention, archiving, or
copying of this communication is strictly prohibited. If you have received
this e-mail in error, please notify the sender immediately by reply e-mail
and delete this message.

**Comment by zdenda145** [comment]
function date() is present in PG too:
`test=# \df date`
`                              List of functions`
`   Schema   | Name | Result data type |     Argument data types     |  Type  `
`------------+------+------------------+-----------------------------+--------`
` pg_catalog | date | date             | abstime                     | normal`
` pg_catalog | date | date             | timestamp without time zone | normal`
` pg_catalog | date | date             | timestamp with time zone    | normal`
`(3 rows)`

**Comment by ahsanhadi** [comment]
On Thu, Mar 12, 2015 at 1:44 PM, zdenda145 <notifications@github.com> wrote:

> function date() is present in PG too:
> test=# \df date
> List of functions
> Schema | Name | Result data type | Argument data types | Type
>
> ------------+------+------------------+-----------------------------+--------
> pg_catalog | date | date | abstime | normal
> pg_catalog | date | date | timestamp without time zone | normal
> pg_catalog | date | date | timestamp with time zone | normal
> (3 rows)
>

Yes you are right..apparently it works when the datatype in mysql table is
date, the error is raised when the datatype at mysql is datetime. Even with
date, we need to find a way to send date in same style as mysql, it didn't
work by tweaking the datestyle parameter in PG.

Ibrar is looking into the issue with datetime and how we can send date in
the same style as mysql. He will has a couple of more things that he need
to look at before he will get to this.




> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EnterpriseDB/mysql_fdw/issues/42#issuecomment-78441967>
> .
>



-- 
Ahsan Hadi
Snr Director Product Development
EnterpriseDB Corporation
The Enterprise Postgres Company

Phone: +92-51-8358874
Mobile: +92-333-5162114

Website: www.enterprisedb.com
EnterpriseDB Blog: http://blogs.enterprisedb.com/
Follow us on Twitter: http://www.twitter.com/enterprisedb

This e-mail message (and any attachment) is intended for the use of the
individual or entity to whom it is addressed. This message contains
information from EnterpriseDB Corporation that may be privileged,
confidential, or exempt from disclosure under applicable law. If you are
not the intended recipient or authorized to receive this for the intended
recipient, any use, dissemination, distribution, retention, archiving, or
copying of this communication is strictly prohibited. If you have received
this e-mail in error, please notify the sender immediately by reply e-mail
and delete this message.

**Comment by ahsanhadi** [comment]
This regression has been fixed.

zdenda, please close if you believe the issue has been fixed.
