### ISSUE TITLE
pg "auto-cast" in stored functions causes mysql syntax error

### ISSUE THREAD

**Issue by kshvakov** [EnterpriseDB/mysql_fdw#44]
```sql
CREATE FOREIGN TABLE foreign_users(
     id bigint,
     username varchar(255)
)
SERVER f_mysql OPTIONS (dbname 'db', table_name 'users');
```
Query ОК
```sql
SELECT U.id FROM foreign_users AS U WHERE U.username = 'test';
  id   
-------
 33088
(1 row)
```

Call function Error

```sql
create or replace function get_user(_username varchar) returns bigint as $$
        SELECT 
            U.id
        FROM foreign_users AS U
        WHERE U.username = _username;
$$ language sql;

select * from  get_user('test');

```

`You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '::character varying))' at line 1`

**Comment by ahsanhadi** [comment]
On Mon, Mar 2, 2015 at 6:54 PM, Kirill Shvakov <notifications@github.com>
wrote:

> CREATE FOREIGN TABLE foreign_users(
>      id bigint,
>      username varchar(255)
> )
> SERVER f_mysql OPTIONS (dbname 'db', table_name 'users');
>
> Query ОК
>
> SELECT U.id FROM foreign_users AS U WHERE U.username = 'test';
>   id   -------
>  33088
> (1 row)
>
> Call function Error
>
> create or replace function get_user(_username varchar) returns bigint as $$
>         SELECT
>             U.id
>         FROM foreign_users AS U
>         WHERE U.username = _username;
> $$ language sql;
> select * from  get_user('test');
>
> You have an error in your SQL syntax; check the manual that corresponds to
> your MySQL server version for the right syntax to use near '::character
> varying))' at line 1
>

This looks a bug...the type casting shouldn't be part of the remote query.

We will try to fix it this week...

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EnterpriseDB/mysql_fdw/issues/44>.
>



-- 
Ahsan Hadi
Snr Director Product Development
EnterpriseDB Corporation
The Enterprise Postgres Company

Phone: +92-51-8358874
Mobile: +92-333-5162114

Website: www.enterprisedb.com
EnterpriseDB Blog: http://blogs.enterprisedb.com/
Follow us on Twitter: http://www.twitter.com/enterprisedb

This e-mail message (and any attachment) is intended for the use of the
individual or entity to whom it is addressed. This message contains
information from EnterpriseDB Corporation that may be privileged,
confidential, or exempt from disclosure under applicable law. If you are
not the intended recipient or authorized to receive this for the intended
recipient, any use, dissemination, distribution, retention, archiving, or
copying of this communication is strictly prohibited. If you have received
this e-mail in error, please notify the sender immediately by reply e-mail
and delete this message.

**Comment by kshvakov** [comment]
Thank you

PS: if I use plpgsql the first 5 queries are executed without errors, the following query error: "syntax error"

```
auth=> select * from  get_user('test');
 get_user 
----------
    33088
(1 row)

auth=> select * from  get_user('test');
 get_user 
----------
    33088
(1 row)

auth=> select * from  get_user('test');
 get_user 
----------
    33088
(1 row)

auth=> select * from  get_user('test');
 get_user 
----------
    33088
(1 row)

auth=> select * from  get_user('test');
 get_user 
----------
    33088
(1 row)

auth=> select * from  get_user('test');
ERROR:  failed to prepare the MySQL query: 
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '::character varying))' at line 1
```

**Comment by ibrarahmad** [comment]
I am able to reproduce the issue and will push the fix for that. Thanks for
the test cases.


On Mon, Mar 2, 2015 at 8:17 PM, Kirill Shvakov <notifications@github.com>
wrote:

> Thank you
>
> PS: if I use plpgsql the first 5 queries are executed without errors, the
> following query error: "syntax error"
>
> auth=> select * from  get_user('test');
>  get_user
> ----------
>     33088
> (1 row)
>
> auth=> select * from  get_user('test');
>  get_user
> ----------
>     33088
> (1 row)
>
> auth=> select * from  get_user('test');
>  get_user
> ----------
>     33088
> (1 row)
>
> auth=> select * from  get_user('test');
>  get_user
> ----------
>     33088
> (1 row)
>
> auth=> select * from  get_user('test');
>  get_user
> ----------
>     33088
> (1 row)
>
> auth=> select * from  get_user('test');
> ERROR:  failed to prepare the MySQL query:
> You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '::character varying))' at line 1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EnterpriseDB/mysql_fdw/issues/44#issuecomment-76729488>
> .
>



-- 
Ibrar Ahmed
EnterpriseDB   http://www.enterprisedb.com

**Comment by kshvakov** [comment]
Segfault after 5 queries (with lang plpgsql, sql - ok)

```
2015-03-10 10:47:32 MSK [15711-7] LOG:  server process (PID 15781) was terminated by signal 11: Segmentation fault
2015-03-10 10:47:32 MSK [15711-8] DETAIL:  Failed process was running: select * from  get_user('test');
2015-03-10 10:47:32 MSK [15711-9] LOG:  terminating any other active server processes
2015-03-10 10:47:32 MSK [15764-2] WARNING:  terminating connection because of crash of another server process
2015-03-10 10:47:32 MSK [15764-3] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2015-03-10 10:47:32 MSK [15764-4] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2015-03-10 10:47:32 MSK [15769-1] postgres@auth WARNING:  terminating connection because of crash of another server process
2015-03-10 10:47:32 MSK [15769-2] postgres@auth DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2015-03-10 10:47:32 MSK [15769-3] postgres@auth HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2015-03-10 10:47:32 MSK [15787-1] auth@auth FATAL:  the database system is in recovery mode
2015-03-10 10:47:32 MSK [15711-10] LOG:  all server processes terminated; reinitializing
2015-03-10 10:47:32 MSK [15788-1] LOG:  database system was interrupted; last known up at 2015-03-10 10:45:43 MSK
2015-03-10 10:47:32 MSK [15788-2] LOG:  database system was not properly shut down; automatic recovery in progress
2015-03-10 10:47:32 MSK [15788-3] LOG:  record with zero length at 0/1D29F48
2015-03-10 10:47:32 MSK [15788-4] LOG:  redo is not required
2015-03-10 10:47:32 MSK [15711-11] LOG:  database system is ready to accept connections
2015-03-10 10:47:32 MSK [15792-1] LOG:  autovacuum launcher started
```

mysql_fdw Branch - master 
PostgreSQL 9.4.1 on x86_64-unknown-linux-gnu, compiled by gcc (Ubuntu 4.8.2-19ubuntu1) 4.8.2, 64-bit
MySql 5.5.40-0+wheezy1-log


```sql

CREATE OR REPLACE FUNCTION get_user(_username character varying)
  RETURNS bigint AS
$BODY$
	declare 
		user_id bigint;
	begin
        SELECT 
            U.id INTO user_id
        FROM foreign_users AS U
        WHERE U.username = _username;

	return user_id;
	
        end;
$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100;
ALTER FUNCTION get_user(character varying)
  OWNER TO auth;
  
```

```sql
CREATE OR REPLACE FUNCTION get_user(_username character varying)
  RETURNS bigint AS
$BODY$

        SELECT 
            U.id
        FROM foreign_users AS U
        WHERE U.username = _username;

$BODY$
  LANGUAGE sql VOLATILE
  COST 100;
ALTER FUNCTION get_user(character varying)
  OWNER TO auth;
```

**Comment by kshvakov** [comment]
syslog

```
Mar 10 10:47:32 localhost kernel: [1018140.595983] postgres[15781]: segfault at 8 ip 00007f70ad3e6d7b sp 00007fffedc2b520 error 4 in postgres[7f70ad022000+582000]

```

**Comment by ahsanhadi** [comment]
We will try to reproduce and get back to you.

On Tue, Mar 10, 2015 at 1:04 PM, Kirill Shvakov <notifications@github.com>
wrote:

> Segfault after 5 queries (with lang plpgsql, sql - ok)
>
> 2015-03-10 10:47:32 MSK [15711-7] LOG:  server process (PID 15781) was terminated by signal 11: Segmentation fault
> 2015-03-10 10:47:32 MSK [15711-8] DETAIL:  Failed process was running: select * from  get_user('test');
> 2015-03-10 10:47:32 MSK [15711-9] LOG:  terminating any other active server processes
> 2015-03-10 10:47:32 MSK [15764-2] WARNING:  terminating connection because of crash of another server process
> 2015-03-10 10:47:32 MSK [15764-3] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
> 2015-03-10 10:47:32 MSK [15764-4] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
> 2015-03-10 10:47:32 MSK [15769-1] postgres@auth WARNING:  terminating connection because of crash of another server process
> 2015-03-10 10:47:32 MSK [15769-2] postgres@auth DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
> 2015-03-10 10:47:32 MSK [15769-3] postgres@auth HINT:  In a moment you should be able to reconnect to the database and repeat your command.
> 2015-03-10 10:47:32 MSK [15787-1] auth@auth FATAL:  the database system is in recovery mode
> 2015-03-10 10:47:32 MSK [15711-10] LOG:  all server processes terminated; reinitializing
> 2015-03-10 10:47:32 MSK [15788-1] LOG:  database system was interrupted; last known up at 2015-03-10 10:45:43 MSK
> 2015-03-10 10:47:32 MSK [15788-2] LOG:  database system was not properly shut down; automatic recovery in progress
> 2015-03-10 10:47:32 MSK [15788-3] LOG:  record with zero length at 0/1D29F48
> 2015-03-10 10:47:32 MSK [15788-4] LOG:  redo is not required
> 2015-03-10 10:47:32 MSK [15711-11] LOG:  database system is ready to accept connections
> 2015-03-10 10:47:32 MSK [15792-1] LOG:  autovacuum launcher started
>
> mysql_fdw Branch - master
> PostgreSQL 9.4.1 on x86_64-unknown-linux-gnu, compiled by gcc (Ubuntu
> 4.8.2-19ubuntu1) 4.8.2, 64-bit
> MySql 5.5.40-0+wheezy1-log
>
> CREATE OR REPLACE FUNCTION get_user(_username character varying)
>   RETURNS bigint AS
> $BODY$
>     declare
>         user_id bigint;
>     begin
>         SELECT
>             U.id INTO user_id
>         FROM foreign_users AS U
>         WHERE U.username = _username;
>
>     return user_id;
>
>         end;
> $BODY$
>   LANGUAGE plpgsql VOLATILE
>   COST 100;ALTER FUNCTION get_user(character varying)
>   OWNER TO auth;
>
> CREATE OR REPLACE FUNCTION get_user(_username character varying)
>   RETURNS bigint AS
> $BODY$
>
>         SELECT
>             U.id
>         FROM foreign_users AS U
>         WHERE U.username = _username;
>
> $BODY$
>   LANGUAGE sql VOLATILE
>   COST 100;ALTER FUNCTION get_user(character varying)
>   OWNER TO auth;
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EnterpriseDB/mysql_fdw/issues/44#issuecomment-78010208>
> .
>



-- 
Ahsan Hadi
Snr Director Product Development
EnterpriseDB Corporation
The Enterprise Postgres Company

Phone: +92-51-8358874
Mobile: +92-333-5162114

Website: www.enterprisedb.com
EnterpriseDB Blog: http://blogs.enterprisedb.com/
Follow us on Twitter: http://www.twitter.com/enterprisedb

This e-mail message (and any attachment) is intended for the use of the
individual or entity to whom it is addressed. This message contains
information from EnterpriseDB Corporation that may be privileged,
confidential, or exempt from disclosure under applicable law. If you are
not the intended recipient or authorized to receive this for the intended
recipient, any use, dissemination, distribution, retention, archiving, or
copying of this communication is strictly prohibited. If you have received
this e-mail in error, please notify the sender immediately by reply e-mail
and delete this message.

**Comment by ahsanhadi** [comment]
Can you please send us stack trace.

On Tue, Mar 10, 2015 at 1:50 PM, Ahsan Hadi <ahsan.hadi@enterprisedb.com>
wrote:

> We will try to reproduce and get back to you.
>
> On Tue, Mar 10, 2015 at 1:04 PM, Kirill Shvakov <notifications@github.com>
> wrote:
>
>> Segfault after 5 queries (with lang plpgsql, sql - ok)
>>
>> 2015-03-10 10:47:32 MSK [15711-7] LOG:  server process (PID 15781) was terminated by signal 11: Segmentation fault
>> 2015-03-10 10:47:32 MSK [15711-8] DETAIL:  Failed process was running: select * from  get_user('test');
>> 2015-03-10 10:47:32 MSK [15711-9] LOG:  terminating any other active server processes
>> 2015-03-10 10:47:32 MSK [15764-2] WARNING:  terminating connection because of crash of another server process
>> 2015-03-10 10:47:32 MSK [15764-3] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
>> 2015-03-10 10:47:32 MSK [15764-4] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
>> 2015-03-10 10:47:32 MSK [15769-1] postgres@auth WARNING:  terminating connection because of crash of another server process
>> 2015-03-10 10:47:32 MSK [15769-2] postgres@auth DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
>> 2015-03-10 10:47:32 MSK [15769-3] postgres@auth HINT:  In a moment you should be able to reconnect to the database and repeat your command.
>> 2015-03-10 10:47:32 MSK [15787-1] auth@auth FATAL:  the database system is in recovery mode
>> 2015-03-10 10:47:32 MSK [15711-10] LOG:  all server processes terminated; reinitializing
>> 2015-03-10 10:47:32 MSK [15788-1] LOG:  database system was interrupted; last known up at 2015-03-10 10:45:43 MSK
>> 2015-03-10 10:47:32 MSK [15788-2] LOG:  database system was not properly shut down; automatic recovery in progress
>> 2015-03-10 10:47:32 MSK [15788-3] LOG:  record with zero length at 0/1D29F48
>> 2015-03-10 10:47:32 MSK [15788-4] LOG:  redo is not required
>> 2015-03-10 10:47:32 MSK [15711-11] LOG:  database system is ready to accept connections
>> 2015-03-10 10:47:32 MSK [15792-1] LOG:  autovacuum launcher started
>>
>> mysql_fdw Branch - master
>> PostgreSQL 9.4.1 on x86_64-unknown-linux-gnu, compiled by gcc (Ubuntu
>> 4.8.2-19ubuntu1) 4.8.2, 64-bit
>> MySql 5.5.40-0+wheezy1-log
>>
>> CREATE OR REPLACE FUNCTION get_user(_username character varying)
>>   RETURNS bigint AS
>> $BODY$
>>     declare
>>         user_id bigint;
>>     begin
>>         SELECT
>>             U.id INTO user_id
>>         FROM foreign_users AS U
>>         WHERE U.username = _username;
>>
>>     return user_id;
>>
>>         end;
>> $BODY$
>>   LANGUAGE plpgsql VOLATILE
>>   COST 100;ALTER FUNCTION get_user(character varying)
>>   OWNER TO auth;
>>
>> CREATE OR REPLACE FUNCTION get_user(_username character varying)
>>   RETURNS bigint AS
>> $BODY$
>>
>>         SELECT
>>             U.id
>>         FROM foreign_users AS U
>>         WHERE U.username = _username;
>>
>> $BODY$
>>   LANGUAGE sql VOLATILE
>>   COST 100;ALTER FUNCTION get_user(character varying)
>>   OWNER TO auth;
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/EnterpriseDB/mysql_fdw/issues/44#issuecomment-78010208>
>> .
>>
>
>
>
> --
> Ahsan Hadi
> Snr Director Product Development
> EnterpriseDB Corporation
> The Enterprise Postgres Company
>
> Phone: +92-51-8358874
> Mobile: +92-333-5162114
>
> Website: www.enterprisedb.com
> EnterpriseDB Blog: http://blogs.enterprisedb.com/
> Follow us on Twitter: http://www.twitter.com/enterprisedb
>
> This e-mail message (and any attachment) is intended for the use of the
> individual or entity to whom it is addressed. This message contains
> information from EnterpriseDB Corporation that may be privileged,
> confidential, or exempt from disclosure under applicable law. If you are
> not the intended recipient or authorized to receive this for the intended
> recipient, any use, dissemination, distribution, retention, archiving, or
> copying of this communication is strictly prohibited. If you have received
> this e-mail in error, please notify the sender immediately by reply e-mail
> and delete this message.
>



-- 
Ahsan Hadi
Snr Director Product Development
EnterpriseDB Corporation
The Enterprise Postgres Company

Phone: +92-51-8358874
Mobile: +92-333-5162114

Website: www.enterprisedb.com
EnterpriseDB Blog: http://blogs.enterprisedb.com/
Follow us on Twitter: http://www.twitter.com/enterprisedb

This e-mail message (and any attachment) is intended for the use of the
individual or entity to whom it is addressed. This message contains
information from EnterpriseDB Corporation that may be privileged,
confidential, or exempt from disclosure under applicable law. If you are
not the intended recipient or authorized to receive this for the intended
recipient, any use, dissemination, distribution, retention, archiving, or
copying of this communication is strictly prohibited. If you have received
this e-mail in error, please notify the sender immediately by reply e-mail
and delete this message.

**Comment by kshvakov** [comment]
```
0x00007ffff63b1913 in select () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007ffff63b1913 in select () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00005555555e85e9 in ServerLoop () at /tmp/buildd/postgresql-9.4-9.4.1/build/../src/backend/postmaster/postmaster.c:1561
#2  0x00005555557c2171 in PostmasterMain (argc=3, argv=<optimized out>)
    at /tmp/buildd/postgresql-9.4-9.4.1/build/../src/backend/postmaster/postmaster.c:1244
#3  0x00005555555e9d33 in main (argc=3, argv=0x555555d4e9e0) at /tmp/buildd/postgresql-9.4-9.4.1/build/../src/backend/main/main.c:228
```
```
[New process 28944]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
2015-03-10 19:22:36 MSK [28935-1] LOG:  database system is ready to accept connections

[New process 28956]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Reading symbols from /usr/lib/debug/.build-id/41/a6f62690852b9a37ea61af9bdabf1bf84b0897.debug...done.
Reading symbols from /usr/lib/postgresql/9.4/lib/mysql_fdw.so...done.
[New Thread 0x7fffe853e700 (LWP 28957)]
[Thread 0x7fffe853e700 (LWP 28957) exited]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff7fc5780 (LWP 28956)]
pfree (pointer=0x555555e18040) at /tmp/buildd/postgresql-9.4-9.4.1/build/../src/backend/utils/mmgr/mcxt.c:709
709	/tmp/buildd/postgresql-9.4-9.4.1/build/../src/backend/utils/mmgr/mcxt.c: Нет такого файла или каталога.
```

```
#0  pfree (pointer=0x555555e18040) at /tmp/buildd/postgresql-9.4-9.4.1/build/../src/backend/utils/mmgr/mcxt.c:709
#1  0x00007fffe8a7cc18 in mysqlEndForeignScan (node=<optimized out>) at mysql_fdw.c:619
#2  0x000055555573fa86 in ExecEndForeignScan (/build/buildd/gdb-7.7.1/gdb/dwarf2loc.c:836: internal-error: chain_candidate: Assertion `result->callers + result->callees < result->length' failed.
```

ps: coredump in progress )

**Comment by kshvakov** [comment]
thank you
