### ISSUE TITLE
Long field names not working?

### ISSUE THREAD

**Issue by InfoSec812** [EnterpriseDB/mysql_fdw#51]
My FDW table schema is:

```
CREATE FOREIGN TABLE liquorstore_backendipaddress (
    id bigint NOT NULL,
    backend_network_id bigint,
    backend_virtual_interface_id bigint,
    address character varying(15) NOT NULL,
    is_gateway boolean NOT NULL,
    is_reserved boolean NOT NULL
)
SERVER edison
OPTIONS (
    dbname 'edison',
    table_name 'liquorstore_backendvirtualinterface'
);
```

But when I run the following query:

```
SELECT
    *
FROM liquorstore_backendipaddress
```

I get an error:

```
ccedison=# SELECT * FROM liquorstore_backendipaddress;
ERROR:  failed to prepare the MySQL query:
Unknown column 'backend_network_id' in 'field list'
```

I still cannot figure out what the problem might be so any help would be GREATLY appreciated.

It appears that all of my other FDW mappings are working correctly, so I suspect that this may be due to the long field names.

**Comment by ibrarahmad** [comment]
It works fine on my computer, can you please send me the schema of mysql
liquorstore_backendvirtualinterface table.

On Sat, Mar 28, 2015 at 1:58 AM, Deven Phillips <notifications@github.com>
wrote:

> My FDW table schema is:
>
> CREATE FOREIGN TABLE liquorstore_backendipaddress (
> id bigint NOT NULL,
> backend_network_id bigint,
> backend_virtual_interface_id bigint,
> address character varying(15) NOT NULL,
> is_gateway boolean NOT NULL,
> is_reserved boolean NOT NULL
> )
> SERVER edison
> OPTIONS (
> dbname 'edison',
> table_name 'liquorstore_backendvirtualinterface'
> );
>
> But when I run the following query:
>
> SELECT
> *
> FROM liquorstore_backendipaddress
>
> I get an error:
>
> ccedison=# SELECT * FROM liquorstore_backendipaddress;
> ERROR: failed to prepare the MySQL query:
> Unknown column 'backend_network_id' in 'field list'
>
> I still cannot figure out what the problem might be so any help would be
> GREATLY appreciated.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EnterpriseDB/mysql_fdw/issues/51>.
>



-- 
Ibrar Ahmed
EnterpriseDB   http://www.enterprisedb.com

**Comment by InfoSec812** [comment]
Yes. Here's the MySQL schema:

CREATE TABLE `liquorstore_backendipaddress` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `backend_network_id` int(11) DEFAULT NULL,
  `backend_virtual_interface_id` int(11) DEFAULT NULL,
  `address` varchar(15) NOT NULL,
  `is_gateway` tinyint(1) NOT NULL,
  `is_reserved` tinyint(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `backend_network_id` (`backend_network_id`,`address`),
  KEY `liquorstore_backendipaddress_4a648124` (`backend_network_id`),
  KEY `liquorstore_backendipaddress_27235e4d`
(`backend_virtual_interface_id`),
  CONSTRAINT `backend_network_id_refs_id_1d869576` FOREIGN KEY
(`backend_network_id`) REFERENCES `liquorstore_backendnetwork` (`id`),
  CONSTRAINT `backend_virtual_interface_id_refs_id_b058eaeb` FOREIGN KEY
(`backend_virtual_interface_id`) REFERENCES
`liquorstore_backendvirtualinterface` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=72184 DEFAULT CHARSET=latin1

Deven Phillips
from my mobile

**Comment by ibrarahmad** [comment]
I asked for schema of "liquorstore_backendvirtualinterface" not the "
liquorstore_backendipaddress" because you have specified

liquorstore_backendvirtualinterface as remote table in create foreign table
statement.


SERVER edison
OPTIONS (
dbname 'edison',
table_name 'liquorstore_backendvirtualinterface'       <----
);

On Sat, Mar 28, 2015 at 2:32 AM, Deven Phillips <notifications@github.com>
wrote:

> Yes. Here's the MySQL schema:
>
> CREATE TABLE `liquorstore_backendipaddress` (
> `id` int(11) NOT NULL AUTO_INCREMENT,
> `backend_network_id` int(11) DEFAULT NULL,
> `backend_virtual_interface_id` int(11) DEFAULT NULL,
> `address` varchar(15) NOT NULL,
> `is_gateway` tinyint(1) NOT NULL,
> `is_reserved` tinyint(1) NOT NULL,
> PRIMARY KEY (`id`),
> UNIQUE KEY `backend_network_id` (`backend_network_id`,`address`),
> KEY `liquorstore_backendipaddress_4a648124` (`backend_network_id`),
> KEY `liquorstore_backendipaddress_27235e4d`
> (`backend_virtual_interface_id`),
> CONSTRAINT `backend_network_id_refs_id_1d869576` FOREIGN KEY
> (`backend_network_id`) REFERENCES `liquorstore_backendnetwork` (`id`),
> CONSTRAINT `backend_virtual_interface_id_refs_id_b058eaeb` FOREIGN KEY
> (`backend_virtual_interface_id`) REFERENCES
> `liquorstore_backendvirtualinterface` (`id`)
> ) ENGINE=InnoDB AUTO_INCREMENT=72184 DEFAULT CHARSET=latin1
>
> Deven Phillips
> from my mobile
> On Mar 27, 2015 5:26 PM, "Ibrar Ahmed" <notifications@github.com> wrote:
>
> > It works fine on my computer, can you please send me the schema of mysql
> > liquorstore_backendvirtualinterface table.
> >
> > On Sat, Mar 28, 2015 at 1:58 AM, Deven Phillips <
> notifications@github.com>
> > wrote:
> >
> > > My FDW table schema is:
> > >
> > > CREATE FOREIGN TABLE liquorstore_backendipaddress (
> > > id bigint NOT NULL,
> > > backend_network_id bigint,
> > > backend_virtual_interface_id bigint,
> > > address character varying(15) NOT NULL,
> > > is_gateway boolean NOT NULL,
> > > is_reserved boolean NOT NULL
> > > )
> > > SERVER edison
> > > OPTIONS (
> > > dbname 'edison',
> > > table_name 'liquorstore_backendvirtualinterface'
> > > );
> > >
> > > But when I run the following query:
> > >
> > > SELECT
> > > *
> > > FROM liquorstore_backendipaddress
> > >
> > > I get an error:
> > >
> > > ccedison=# SELECT * FROM liquorstore_backendipaddress;
> > > ERROR: failed to prepare the MySQL query:
> > > Unknown column 'backend_network_id' in 'field list'
> > >
> > > I still cannot figure out what the problem might be so any help would
> be
> > > GREATLY appreciated.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/EnterpriseDB/mysql_fdw/issues/51>.
> > >
> >
> >
> >
> > --
> > Ibrar Ahmed
> > EnterpriseDB http://www.enterprisedb.com
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/EnterpriseDB/mysql_fdw/issues/51#issuecomment-87096828>
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EnterpriseDB/mysql_fdw/issues/51#issuecomment-87097665>
> .
>



-- 
Ibrar Ahmed
EnterpriseDB   http://www.enterprisedb.com

**Comment by InfoSec812** [comment]
Whoops!

Deven Phillips
from my mobile

**Comment by InfoSec812** [comment]
Well, that question solved my problem altogether... I had mapped the wrong
table!!

Thanks Ibrar!

Deven
