### ISSUE TITLE
Repeating options parsing.

### ISSUE THREAD

**Issue by CodingFeles** [EnterpriseDB/mysql_fdw#56]
In mysql_fdw.c within mysqlGetForeignRelSize function you have two identical consecutive calls:

```
/* Fetch the options */
options = mysql_get_options(foreigntableid);

/* Fetch options */
options = mysql_get_options(foreigntableid);
```

This are [655 - 659](https://github.com/EnterpriseDB/mysql_fdw/blob/master/mysql_fdw.c#L655) lines.

**Comment by ahsanhadi** [comment]
@ibrarahmad Please take care of this...

**Comment by CodingFeles** [comment]
[Looks like it's fixed.](https://github.com/EnterpriseDB/mysql_fdw/blob/master/mysql_fdw.c#L801)
