### ISSUE TITLE
DELETE causes "server closed the connection unexpectedly" Error

### ISSUE THREAD

**Issue by JamuelStarkey** [EnterpriseDB/mysql_fdw#57]
I set up a simple FOREIGN table to mysql (v 5.1.71) using both today's master and the REL_2_0_1 versions and whenever I issue a DELETE FROM I always get this error:

`
postgres=# delete from tester where dir='ABC';

server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
!> 
`

I'm a PG noob so I don't really know where to start troubleshooting but if I reconnect I see that the delete actually completed (the row is gone).  I'm guessing I must be doing something really stupid as the build and install of the fdw was super easy/pain free.  I created the foreign table and all of the dependencies following the example in the README.

Any ideas on where I can start to figure out what's going on?  FWIW I don't see any error in the mysql log.

Thanks,

JPS

**Comment by ahsanhadi** [comment]
We will look into this and get back to you. The sever shouldn't crash on a
simple delete statement.

Can you send your complete test case please.


On Wed, May 13, 2015 at 10:03 AM, JamuelStarkey <notifications@github.com>
wrote:

> I set up a simple FOREIGN table to mysql (v 5.1.71) using both today's
> master and the REL_2_0_1 versions and whenever I issue a DELETE FROM I
> always get this error:
>
> `
> postgres=# delete from tester where dir='ABC';
>
> server closed the connection unexpectedly
> This probably means the server terminated abnormally
> before or while processing the request.
> The connection to the server was lost. Attempting reset: Failed.
> !>
> `
>
> I'm a PG noob so I don't really know where to start troubleshooting but if
> I reconnect I see that the delete actually completed (the row is gone). I'm
> guessing I must be doing something really stupid as the build and install
> of the fdw was super easy/pain free. I created the foreign table and all of
> the dependencies following the example in the README.
>
> Any ideas on where I can start to figure out what's going on? FWIW I don't
> see any error in the mysql log.
>
> Thanks,
>
> JPS
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EnterpriseDB/mysql_fdw/issues/57>.
>



-- 
Ahsan Hadi
Snr Director Product Development
EnterpriseDB Corporation
The Enterprise Postgres Company

Phone: +92-51-8358874
Mobile: +92-333-5162114

Website: www.enterprisedb.com
EnterpriseDB Blog: http://blogs.enterprisedb.com/
Follow us on Twitter: http://www.twitter.com/enterprisedb

This e-mail message (and any attachment) is intended for the use of the
individual or entity to whom it is addressed. This message contains
information from EnterpriseDB Corporation that may be privileged,
confidential, or exempt from disclosure under applicable law. If you are
not the intended recipient or authorized to receive this for the intended
recipient, any use, dissemination, distribution, retention, archiving, or
copying of this communication is strictly prohibited. If you have received
this e-mail in error, please notify the sender immediately by reply e-mail
and delete this message.

**Comment by ibrarahmad** [comment]
I have just verified on my computer and all works fine on my computer, a
complete test case can help.

postgres=# CREATE EXTENSION mysql_fdw;
CREATE EXTENSION
postgres=# CREATE SERVER mysql_svr FOREIGN DATA WRAPPER mysql_fdw;
CREATE SERVER
postgres=# CREATE USER MAPPING FOR ibrar SERVER mysql_svr OPTIONS(username
'foo', password 'bar');
CREATE USER MAPPING
postgres=# CREATE FOREIGN TABLE emp_test(emp_id int, emp_name text,
emp_dept_id int) SERVER mysql_svr OPTIONS(dbname 'testdb', table_name
'employee');
CREATE FOREIGN TABLE
postgres=# select * from emp_test;
 emp_id | emp_name | emp_dept_id
--------+----------+-------------
(0 rows)

postgres=# insert into emp_test values(1,'Name', 1);
INSERT 0 1
postgres=# insert into emp_test values(2,'Name2', 2);
INSERT 0 1
postgres=# insert into emp_test values(3,'Name2', 3);
INSERT 0 1
postgres=# delete from emp_test;
DELETE 3


On Wed, May 13, 2015 at 5:02 PM, Ahsan Hadi <notifications@github.com>
wrote:

> We will look into this and get back to you. The sever shouldn't crash on a
> simple delete statement.
>
> Can you send your complete test case please.
>
>
> On Wed, May 13, 2015 at 10:03 AM, JamuelStarkey <notifications@github.com>
> wrote:
>
>
> > I set up a simple FOREIGN table to mysql (v 5.1.71) using both today's
> > master and the REL_2_0_1 versions and whenever I issue a DELETE FROM I
> > always get this error:
> >
> > `
> > postgres=# delete from tester where dir='ABC';
> >
> > server closed the connection unexpectedly
> > This probably means the server terminated abnormally
> > before or while processing the request.
> > The connection to the server was lost. Attempting reset: Failed.
> > !>
> > `
> >
> > I'm a PG noob so I don't really know where to start troubleshooting but
> if
> > I reconnect I see that the delete actually completed (the row is gone).
> I'm
> > guessing I must be doing something really stupid as the build and install
> > of the fdw was super easy/pain free. I created the foreign table and all
> of
> > the dependencies following the example in the README.
> >
> > Any ideas on where I can start to figure out what's going on? FWIW I
> don't
> > see any error in the mysql log.
> >
> > Thanks,
> >
> > JPS
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/EnterpriseDB/mysql_fdw/issues/57>.
> >
>
>
>
> --
> Ahsan Hadi
> Snr Director Product Development
> EnterpriseDB Corporation
> The Enterprise Postgres Company
>
> Phone: +92-51-8358874
> Mobile: +92-333-5162114
>
> Website: www.enterprisedb.com
> EnterpriseDB Blog: http://blogs.enterprisedb.com/
> Follow us on Twitter: http://www.twitter.com/enterprisedb
>
> This e-mail message (and any attachment) is intended for the use of the
> individual or entity to whom it is addressed. This message contains
> information from EnterpriseDB Corporation that may be privileged,
> confidential, or exempt from disclosure under applicable law. If you are
> not the intended recipient or authorized to receive this for the intended
> recipient, any use, dissemination, distribution, retention, archiving, or
> copying of this communication is strictly prohibited. If you have received
> this e-mail in error, please notify the sender immediately by reply e-mail
> and delete this message.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EnterpriseDB/mysql_fdw/issues/57#issuecomment-101642152>
> .
>



-- 
Ibrar Ahmed
EnterpriseDB   http://www.enterprisedb.com

**Comment by ahsanhadi** [comment]
Please try delete with a where clause...

On Wed, May 13, 2015 at 5:21 PM, Ibrar Ahmed <notifications@github.com>
wrote:

> I have just verified on my computer and all works fine on my computer, a
> complete test case can help.
>
> postgres=# CREATE EXTENSION mysql_fdw;
> CREATE EXTENSION
> postgres=# CREATE SERVER mysql_svr FOREIGN DATA WRAPPER mysql_fdw;
> CREATE SERVER
> postgres=# CREATE USER MAPPING FOR ibrar SERVER mysql_svr OPTIONS(username
> 'foo', password 'bar');
> CREATE USER MAPPING
> postgres=# CREATE FOREIGN TABLE emp_test(emp_id int, emp_name text,
> emp_dept_id int) SERVER mysql_svr OPTIONS(dbname 'testdb', table_name
> 'employee');
> CREATE FOREIGN TABLE
> postgres=# select * from emp_test;
> emp_id | emp_name | emp_dept_id
> --------+----------+-------------
> (0 rows)
>
> postgres=# insert into emp_test values(1,'Name', 1);
> INSERT 0 1
> postgres=# insert into emp_test values(2,'Name2', 2);
> INSERT 0 1
> postgres=# insert into emp_test values(3,'Name2', 3);
> INSERT 0 1
> postgres=# delete from emp_test;
> DELETE 3
>
>
> On Wed, May 13, 2015 at 5:02 PM, Ahsan Hadi <notifications@github.com>
> wrote:
>
> > We will look into this and get back to you. The sever shouldn't crash on
> a
> > simple delete statement.
> >
> > Can you send your complete test case please.
> >
> >
> > On Wed, May 13, 2015 at 10:03 AM, JamuelStarkey <
> notifications@github.com>
> > wrote:
> >
> >
> > > I set up a simple FOREIGN table to mysql (v 5.1.71) using both today's
> > > master and the REL_2_0_1 versions and whenever I issue a DELETE FROM I
> > > always get this error:
> > >
> > > `
> > > postgres=# delete from tester where dir='ABC';
> > >
> > > server closed the connection unexpectedly
> > > This probably means the server terminated abnormally
> > > before or while processing the request.
> > > The connection to the server was lost. Attempting reset: Failed.
> > > !>
> > > `
> > >
> > > I'm a PG noob so I don't really know where to start troubleshooting but
> > if
> > > I reconnect I see that the delete actually completed (the row is gone).
> > I'm
> > > guessing I must be doing something really stupid as the build and
> install
> > > of the fdw was super easy/pain free. I created the foreign table and
> all
> > of
> > > the dependencies following the example in the README.
> > >
> > > Any ideas on where I can start to figure out what's going on? FWIW I
> > don't
> > > see any error in the mysql log.
> > >
> > > Thanks,
> > >
> > > JPS
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/EnterpriseDB/mysql_fdw/issues/57>.
> > >
> >
> >
> >
> > --
> > Ahsan Hadi
> > Snr Director Product Development
> > EnterpriseDB Corporation
> > The Enterprise Postgres Company
> >
> > Phone: +92-51-8358874
> > Mobile: +92-333-5162114
> >
> > Website: www.enterprisedb.com
> > EnterpriseDB Blog: http://blogs.enterprisedb.com/
> > Follow us on Twitter: http://www.twitter.com/enterprisedb
> >
> > This e-mail message (and any attachment) is intended for the use of the
> > individual or entity to whom it is addressed. This message contains
> > information from EnterpriseDB Corporation that may be privileged,
> > confidential, or exempt from disclosure under applicable law. If you are
> > not the intended recipient or authorized to receive this for the intended
> > recipient, any use, dissemination, distribution, retention, archiving, or
> > copying of this communication is strictly prohibited. If you have
> received
> > this e-mail in error, please notify the sender immediately by reply
> e-mail
> > and delete this message.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/EnterpriseDB/mysql_fdw/issues/57#issuecomment-101642152
> >
> > .
> >
>
>
>
> --
> Ibrar Ahmed
> EnterpriseDB http://www.enterprisedb.com
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EnterpriseDB/mysql_fdw/issues/57#issuecomment-101646023>
> .
>



-- 
Ahsan Hadi
Snr Director Product Development
EnterpriseDB Corporation
The Enterprise Postgres Company

Phone: +92-51-8358874
Mobile: +92-333-5162114

Website: www.enterprisedb.com
EnterpriseDB Blog: http://blogs.enterprisedb.com/
Follow us on Twitter: http://www.twitter.com/enterprisedb

This e-mail message (and any attachment) is intended for the use of the
individual or entity to whom it is addressed. This message contains
information from EnterpriseDB Corporation that may be privileged,
confidential, or exempt from disclosure under applicable law. If you are
not the intended recipient or authorized to receive this for the intended
recipient, any use, dissemination, distribution, retention, archiving, or
copying of this communication is strictly prohibited. If you have received
this e-mail in error, please notify the sender immediately by reply e-mail
and delete this message.

**Comment by ibrarahmad** [comment]
It works fine too.


postgres=# \d emp_test
         Foreign table "public.emp_test"
   Column    |  Type   | Modifiers | FDW Options
-------------+---------+-----------+-------------
 emp_id      | integer |           |
 emp_name    | text    |           |
 emp_dept_id | integer |           |
Server: mysql_svr
FDW Options: (dbname 'testdb', table_name 'employee')

postgres=# delete from emp_test where emp_name='Hello';
DELETE 0
postgres=# insert into emp_test values(1,'Name1', 1);
INSERT 0 1
postgres=# insert into emp_test values(2,'Name2', 2);
INSERT 0 1
postgres=# insert into emp_test values(3,'Name2', 3);
INSERT 0 1
postgres=# delete from emp_test where emp_name='Name1';
DELETE 1

*postgres=# delete from emp_test where emp_name='Name2';DELETE 2*


On Wed, May 13, 2015 at 5:27 PM, Ahsan Hadi <notifications@github.com>
wrote:

> Please try delete with a where clause...
>
> On Wed, May 13, 2015 at 5:21 PM, Ibrar Ahmed <notifications@github.com>
> wrote:
>
>
> > I have just verified on my computer and all works fine on my computer, a
> > complete test case can help.
> >
> > postgres=# CREATE EXTENSION mysql_fdw;
> > CREATE EXTENSION
> > postgres=# CREATE SERVER mysql_svr FOREIGN DATA WRAPPER mysql_fdw;
> > CREATE SERVER
> > postgres=# CREATE USER MAPPING FOR ibrar SERVER mysql_svr
> OPTIONS(username
> > 'foo', password 'bar');
> > CREATE USER MAPPING
> > postgres=# CREATE FOREIGN TABLE emp_test(emp_id int, emp_name text,
> > emp_dept_id int) SERVER mysql_svr OPTIONS(dbname 'testdb', table_name
> > 'employee');
> > CREATE FOREIGN TABLE
> > postgres=# select * from emp_test;
> > emp_id | emp_name | emp_dept_id
> > --------+----------+-------------
> > (0 rows)
> >
> > postgres=# insert into emp_test values(1,'Name', 1);
> > INSERT 0 1
> > postgres=# insert into emp_test values(2,'Name2', 2);
> > INSERT 0 1
> > postgres=# insert into emp_test values(3,'Name2', 3);
> > INSERT 0 1
> > postgres=# delete from emp_test;
> > DELETE 3
> >
> >
> > On Wed, May 13, 2015 at 5:02 PM, Ahsan Hadi <notifications@github.com>
> > wrote:
> >
> > > We will look into this and get back to you. The sever shouldn't crash
> on
> > a
> > > simple delete statement.
> > >
> > > Can you send your complete test case please.
> > >
> > >
> > > On Wed, May 13, 2015 at 10:03 AM, JamuelStarkey <
> > notifications@github.com>
> > > wrote:
> > >
> > >
> > > > I set up a simple FOREIGN table to mysql (v 5.1.71) using both
> today's
> > > > master and the REL_2_0_1 versions and whenever I issue a DELETE FROM
> I
> > > > always get this error:
> > > >
> > > > `
> > > > postgres=# delete from tester where dir='ABC';
> > > >
> > > > server closed the connection unexpectedly
> > > > This probably means the server terminated abnormally
> > > > before or while processing the request.
> > > > The connection to the server was lost. Attempting reset: Failed.
> > > > !>
> > > > `
> > > >
> > > > I'm a PG noob so I don't really know where to start troubleshooting
> but
> > > if
> > > > I reconnect I see that the delete actually completed (the row is
> gone).
> > > I'm
> > > > guessing I must be doing something really stupid as the build and
> > install
> > > > of the fdw was super easy/pain free. I created the foreign table and
> > all
> > > of
> > > > the dependencies following the example in the README.
> > > >
> > > > Any ideas on where I can start to figure out what's going on? FWIW I
> > > don't
> > > > see any error in the mysql log.
> > > >
> > > > Thanks,
> > > >
> > > > JPS
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/EnterpriseDB/mysql_fdw/issues/57>.
> > > >
> > >
> > >
> > >
> > > --
> > > Ahsan Hadi
> > > Snr Director Product Development
> > > EnterpriseDB Corporation
> > > The Enterprise Postgres Company
> > >
> > > Phone: +92-51-8358874
> > > Mobile: +92-333-5162114
> > >
> > > Website: www.enterprisedb.com
> > > EnterpriseDB Blog: http://blogs.enterprisedb.com/
> > > Follow us on Twitter: http://www.twitter.com/enterprisedb
> > >
> > > This e-mail message (and any attachment) is intended for the use of the
> > > individual or entity to whom it is addressed. This message contains
> > > information from EnterpriseDB Corporation that may be privileged,
> > > confidential, or exempt from disclosure under applicable law. If you
> are
> > > not the intended recipient or authorized to receive this for the
> intended
> > > recipient, any use, dissemination, distribution, retention, archiving,
> or
> > > copying of this communication is strictly prohibited. If you have
> > received
> > > this e-mail in error, please notify the sender immediately by reply
> > e-mail
> > > and delete this message.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/EnterpriseDB/mysql_fdw/issues/57#issuecomment-101642152
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Ibrar Ahmed
> > EnterpriseDB http://www.enterprisedb.com
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/EnterpriseDB/mysql_fdw/issues/57#issuecomment-101646023
> >
> > .
> >
>
>
>
> --
> Ahsan Hadi
> Snr Director Product Development
> EnterpriseDB Corporation
> The Enterprise Postgres Company
>
> Phone: +92-51-8358874
> Mobile: +92-333-5162114
>
> Website: www.enterprisedb.com
> EnterpriseDB Blog: http://blogs.enterprisedb.com/
> Follow us on Twitter: http://www.twitter.com/enterprisedb
>
> This e-mail message (and any attachment) is intended for the use of the
> individual or entity to whom it is addressed. This message contains
> information from EnterpriseDB Corporation that may be privileged,
> confidential, or exempt from disclosure under applicable law. If you are
> not the intended recipient or authorized to receive this for the intended
> recipient, any use, dissemination, distribution, retention, archiving, or
> copying of this communication is strictly prohibited. If you have received
> this e-mail in error, please notify the sender immediately by reply e-mail
> and delete this message.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EnterpriseDB/mysql_fdw/issues/57#issuecomment-101648658>
> .
>



-- 
Ibrar Ahmed
EnterpriseDB   http://www.enterprisedb.com

**Comment by JamuelStarkey** [comment]
Here's how I set up a test:

From mysql:
mysql> create database test;
Query OK, 1 row affected (0.04 sec)

mysql> grant select, insert, delete, update, show view, create view on test.* to 'testuser'@'127.0.0.1' identified by 'realsecret';
Query OK, 0 rows affected (0.06 sec)

mysql> use test   
Database changed

mysql> create table tester (id int(11) not null auto_increment primary key, msgnum int(11), data varchar(80));
Query OK, 0 rows affected (0.01 sec)

Then from PG:

postgres=# CREATE EXTENSION mysql_fdw;
CREATE EXTENSION

postgres=# CREATE SERVER mysql_server FOREIGN DATA WRAPPER mysql_fdw OPTIONS (host '127.0.0.1', port '3306');
CREATE SERVER

postgres=# CREATE USER MAPPING FOR postgres SERVER mysql_server OPTIONS (username 'testuser', password 'realsecret');
CREATE USER MAPPING

postgres=# CREATE FOREIGN TABLE tester(id bigint, msgnum bigint, data varchar(80)) SERVER mysql_server OPTIONS (dbname 'test', table_name 'tester');
CREATE FOREIGN TABLE

postgres=# insert into tester values(0,1,'Test 1');
INSERT 0 1

postgres=# insert into tester values(0,2,'Test 2');
INSERT 0 1

postgres=# insert into tester values(0,3,'Test 3');
INSERT 0 1


postgres=# select * from tester;
 id | msgnum |  data  
----+--------+--------
  1 |      1 | Test 1
  2 |      2 | Test 2
  3 |      3 | Test 3
(3 rows)

postgres=# delete from tester where msgnum = 2;
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
!> 

And for the sake of being complete:

# rpm -qa | grep postgres
postgresql94-9.4.1-1PGDG.rhel5
postgresql94-devel-9.4.1-1PGDG.rhel5
postgresql94-jdbc-9.3.1101-1PGDG.rhel5
postgresql94-test-9.4.1-1PGDG.rhel5
postgresql94-jdbc-debuginfo-9.3.1101-1PGDG.rhel5
postgresql94-pltcl-9.4.1-1PGDG.rhel5
postgresql94-python-4.1.1-1PGDG.rhel5
postgresql94-docs-9.4.1-1PGDG.rhel5
postgresql-libs-8.1.23-10.el5_10
postgresql-odbc-08.01.0200-3.1
postgresql94-libs-9.4.1-1PGDG.rhel5
postgresql94-server-9.4.1-1PGDG.rhel5
postgresql94-plperl-9.4.1-1PGDG.rhel5
postgresql94-odbc-09.03.0400-1PGDG.rhel5
postgresql94-debuginfo-9.4.1-1PGDG.rhel5
postgresql-odbc64-09.00.0200-1.el5
postgresql94-plpython-9.4.1-1PGDG.rhel5
postgresql94-python-debuginfo-4.1.1-1PGDG.rhel5
postgresql94-odbc-debuginfo-09.03.0400-1PGDG.rhel5
postgresql94-contrib-9.4.1-1PGDG.rhel5

# rpm -qa | grep -i MySQL
MySQL-server-community-5.1.71-1.rhel5
perl-DBD-MySQL-3.0007-2.el5
MySQL-shared-community-5.1.71-1.rhel5
MySQL-client-community-5.1.71-1.rhel5
mysql-connector-odbc-5.3.4-1.rhel5
MySQL-devel-community-5.1.71-1.rhel5
php-mysql-5.1.6-45.el5_11
php-pear-MDB2-Driver-mysql-1.4.1-3.el5.centos
MySQL-shared-compat-5.1.71-1.rhel5

# uname -a
Linux ASTERISK18.hcvoip.com 2.6.18-402.el5xen #1 SMP Tue Feb 10 19:09:17 EST 2015 i686 i686 i386 GNU/Linux

# cat /etc/redhat-release 
CentOS release 5.11 (Final)

Thanks again for all of your help!

Cheers,

JPS

**Comment by JamuelStarkey** [comment]
Updating to MySQL 5.5.40 seemed to resolve this issue.  I'm guessing 5.1 is emitting something that the fdw is not expecting.  Should I close this issue and you update the docs to say not quite compatible with MySQL 5.1 or would you like to keep it open?

**Comment by ibrarahmad** [comment]
The test case works fine for me. Don't close that issue, I will check that
with older version of MySQL.

On Thu, May 14, 2015 at 12:57 AM, JamuelStarkey <notifications@github.com>
wrote:

> Updating to MySQL 5.5.40 seemed to resolve this issue. I'm guessing 5.1 is
> emitting something that the fdw is not expecting. Should I close this issue
> and you update the docs to say not quite compatible with MySQL 5.1 or would
> you like to keep it open?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EnterpriseDB/mysql_fdw/issues/57#issuecomment-101796071>
> .
>



-- 
Ibrar Ahmed
EnterpriseDB   http://www.enterprisedb.com

**Comment by ahsanhadi** [comment]
I also tested with mysql 5.6.19 and it doesn't crash for me either.



On Thu, May 14, 2015 at 12:59 AM, Ibrar Ahmed <notifications@github.com>
wrote:

> The test case works fine for me. Don't close that issue, I will check that
> with older version of MySQL.
>
> On Thu, May 14, 2015 at 12:57 AM, JamuelStarkey <notifications@github.com>
> wrote:
>
> > Updating to MySQL 5.5.40 seemed to resolve this issue. I'm guessing 5.1
> is
> > emitting something that the fdw is not expecting. Should I close this
> issue
> > and you update the docs to say not quite compatible with MySQL 5.1 or
> would
> > you like to keep it open?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/EnterpriseDB/mysql_fdw/issues/57#issuecomment-101796071
> >
> > .
> >
>
>
>
> --
> Ibrar Ahmed
> EnterpriseDB http://www.enterprisedb.com
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EnterpriseDB/mysql_fdw/issues/57#issuecomment-101796500>
> .
>



-- 
Ahsan Hadi
Snr Director Product Development
EnterpriseDB Corporation
The Enterprise Postgres Company

Phone: +92-51-8358874
Mobile: +92-333-5162114

Website: www.enterprisedb.com
EnterpriseDB Blog: http://blogs.enterprisedb.com/
Follow us on Twitter: http://www.twitter.com/enterprisedb

This e-mail message (and any attachment) is intended for the use of the
individual or entity to whom it is addressed. This message contains
information from EnterpriseDB Corporation that may be privileged,
confidential, or exempt from disclosure under applicable law. If you are
not the intended recipient or authorized to receive this for the intended
recipient, any use, dissemination, distribution, retention, archiving, or
copying of this communication is strictly prohibited. If you have received
this e-mail in error, please notify the sender immediately by reply e-mail
and delete this message.
