### ISSUE TITLE
query one of mysql fdw table,the where condition is using json

### ISSUE THREAD

**Issue by lester015** [EnterpriseDB/mysql_fdw#58]
1. the table pro_json is contain two columns just like that
  id int,instance text
  1, '{"userid":"10001","version":"1.2"}
  2, '{"userid":"10002","version":"1.3"}

2. PostgreSQL
 1. CREATE FOREIGN TABLE fdw_project_json(
     id int,
     instance json)
SERVER mysql_server
     OPTIONS (dbname 'osns', table_name 'pro_json');

 2. PostgreSQL's sql running as follows:
select id,instance::json->>'version' as version from fdw_project_json where (instance::json->>'version')::text = '1.2'
it's cannot running...  how can I query the  json  using where condition. thanks!

**Comment by ahsanhadi** [comment]
I can get the following query to work and return correct results :

edb=# select * from fdw_project_json where instance::json->>'version' =
'1.2' ;
2015-05-23 19:10:19 PKT LOG:  statement: select * from fdw_project_json
where instance::json->>'version' = '1.2' ;
 id |              instance
----+------------------------------------
  1 | {"userid":"10001","version":"1.2"}
(1 row)

Btw I wasn't able to insert into foreign table from PG, it was returning
the following error :

edb=# insert into fdw_project_json values (6,
'{"userid":"10001","version":"1.2"}');
2015-05-23 19:14:30 PKT LOG:  statement: insert into fdw_project_json
values (6, '{"userid":"10001","version":"1.2"}');
2015-05-23 19:14:30 PKT ERROR:  cannot convert constant value to MySQL value
2015-05-23 19:14:30 PKT HINT:  Constant value data type: 114
2015-05-23 19:14:30 PKT STATEMENT:  insert into fdw_project_json values (6,
'{"userid":"10001","version":"1.2"}');
ERROR:  cannot convert constant value to MySQL value
HINT:  Constant value data type: 114
edb=#

Ibrar, Can you look at the insert issue...do we expect it to work.




On Wed, Jun 10, 2015 at 3:44 AM, lester015 <notifications@github.com> wrote:

>
>    1.
>
>    the table pro_json is contain two columns just like that
>    id int,instance text
>    1, '{"userid":"10001","version":"1.2"}
>    2, '{"userid":"10002","version":"1.3"}
>    2.
>
>    PostgreSQL
>     1.
>
>       CREATE FOREIGN TABLE fdw_project_json(
>       id int,
>       instance json)
>       SERVER mysql_server
>       OPTIONS (dbname 'osns', table_name 'pro_json');
>       2.
>
>       PostgreSQL's sql running as follows:
>       select id,instance::json->>'version' as version from
>       fdw_project_json where (instance::json->>'version')::text = '1.2'
>       it's cannot running... how can I query the json using where
>       condition. thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EnterpriseDB/mysql_fdw/issues/58>.
>



-- 
Ahsan Hadi
Snr Director Product Development
EnterpriseDB Corporation
The Enterprise Postgres Company

Phone: +92-51-8358874
Mobile: +92-333-5162114

Website: www.enterprisedb.com
EnterpriseDB Blog: http://blogs.enterprisedb.com/
Follow us on Twitter: http://www.twitter.com/enterprisedb

This e-mail message (and any attachment) is intended for the use of the
individual or entity to whom it is addressed. This message contains
information from EnterpriseDB Corporation that may be privileged,
confidential, or exempt from disclosure under applicable law. If you are
not the intended recipient or authorized to receive this for the intended
recipient, any use, dissemination, distribution, retention, archiving, or
copying of this communication is strictly prohibited. If you have received
this e-mail in error, please notify the sender immediately by reply e-mail
and delete this message.

**Comment by lester015** [comment]
hi hadi,
     I'm copy your the PG sql and the running result as follows:

reports=#  select * from fdw_project_json where instance::json->>'version' = '1.2' ;
ERROR:  failed to prepare the MySQL query: 
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '>> 'version') = '1.2'))' at line 1

BTW, I'm running this sql is ok

reports=#  select id,instance::json->>'version' as version from fdw_project_json;
 id | version 
----+---------
  1 | 1.2
  2 | 1.3
(2 rows)


reports=# select id,instance::json->>'version' as version from fdw_project_json where (instance::json->>'version')::text = '1.2';
ERROR:  failed to prepare the MySQL query: 
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '>> 'version') = '1.2'))' at line 1


if i add the where condition it's will has the wrong . it's seem MySQL Syntax problem.But I running this sql on the PG it  running correctly.  

I running the insert sql,the result as follows:

 insert into fdw_project_json values (3,'{"userid":"10003","version":"1.3"}');
ERROR:  cannot convert constant value to MySQL value
HINT:  Constant value data type: 114

as seem as yours!

**Comment by lester015** [comment]
it's seem MySQL Syntax problem.But I running this sql on the PG it running correctly.as details:

the json_test table is created on PG,it's not using the fdw and running correctly.
reports=# select * from json_test where info::json->>'version' ='1.3' ;
 id |                info                
----+------------------------------------
  3 | {"userid":"10003","version":"1.3"}
(1 row)


the fdw_project_json is refer to pro_json  of Mysql's table which is using fdw and has the problems.

**Comment by ibrarahmad** [comment]
Both the queries works fine on my computer. Ahsan Hadi can you please try these on your computer.

Without Where clause

postgres=#  select id,instance::json->>'version' as version from fdw_project_json;
 id | version 
----+---------
  1 | 1.2
  2 | 1.3
(2 rows)

With Where Clause
postgres=# select id,instance::json->>'version' as version from fdw_project_json where (instance::json->>'version')::text = '1.2';
 id | version 
----+---------
  1 | 1.2
(1 row)

**Comment by ahsanhadi** [comment]
This issue is resolved by the last commit form Ibrar.
