### ISSUE TITLE
btrim does not exist

### ISSUE THREAD

**Issue by studdugie** [EnterpriseDB/mysql_fdw#70]
I have a MySQL/PHP app that I want to port to PostgreSQL so I just installed the mysql_fdw from https://github.com/EnterpriseDB/mysql_fdw because I'd like to do the data migration in SQL if possible.

Installation and set up worked flawlessly but when I run the following query
```
SELECT
  title,
  description,
  '[' || starts || ', ' || COALESCE(ends, 'infinity') || ']'
FROM
  _filler
WHERE
  starts IS NOT NULL
  AND description IS NOT NULL
  AND LENGTH(TRIM(title)) > 0
  AND LENGTH(TRIM(description)) > 0;
```
​I get the following error:​
​ ​

​ERROR:  failed to prepare the MySQL query:
FUNCTION latest.btrim does not exist

FYI: Tables names that start w/ _ are the MySQL versions of PostgreSQL tables.​

My PostgreSQL version is 9.5beta1 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 4.9.2-10ubuntu13) 4.9.2, 64-bit.

My MySQL version is 5.6.27-0ubuntu1.

**Comment by ahsanhadi** [comment]
Can you please share the table ddl to reproduce the issue.

On Thu, Oct 29, 2015 at 7:31 PM, Dane <notifications@github.com> wrote:

> I have a MySQL/PHP app that I want to port to PostgreSQL so I just
> installed the mysql_fdw from https://github.com/EnterpriseDB/mysql_fdw
> because I'd like to do the data migration in SQL if possible.
>
> Installation and set up worked flawlessly but when I run the following
> query
> SELECT
> title,
> description,
> '[' || starts || ', ' || COALESCE(ends, 'infinity') || ']'
> FROM
> _filler
> WHERE
> starts IS NOT NULL
> AND description IS NOT NULL
> AND LENGTH(TRIM(title)) > 0
> AND LENGTH(TRIM(description)) > 0;
>
> ​I get the following error:​
> ​ ​
>
> ​ERROR: failed to prepare the MySQL query:
> FUNCTION latest.btrim does not exist
>
> FYI: Tables names that start w/ _ are the MySQL versions of PostgreSQL
> tables.​
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EnterpriseDB/mysql_fdw/issues/70>.
>



-- 
Ahsan Hadi
Snr Director Product Development
EnterpriseDB Corporation
The Enterprise Postgres Company

Phone: +92-51-8358874
Mobile: +92-333-5162114

Website: www.enterprisedb.com
EnterpriseDB Blog: http://blogs.enterprisedb.com/
Follow us on Twitter: http://www.twitter.com/enterprisedb

This e-mail message (and any attachment) is intended for the use of the
individual or entity to whom it is addressed. This message contains
information from EnterpriseDB Corporation that may be privileged,
confidential, or exempt from disclosure under applicable law. If you are
not the intended recipient or authorized to receive this for the intended
recipient, any use, dissemination, distribution, retention, archiving, or
copying of this communication is strictly prohibited. If you have received
this e-mail in error, please notify the sender immediately by reply e-mail
and delete this message.

**Comment by studdugie** [comment]
CREATE TABLE filler(
  id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(140) NOT NULL,
  description TEXT,
  starts DATETIME,
  ends DATETIME,
  image VARCHAR(255),
  INDEX (starts)
)DEFAULT CHARACTER SET UTF8;

**Comment by studdugie** [comment]
Hi,
Just wondering if anyone is working on this. If so I'll continue w/ the expectation that it will be fixed otherwise I'll need to work around the issue by copying all the tables as temporary tables to PostgreSQL. So if someone could let me know which way to go I would appreciate it.

**Comment by ibrarahmad** [comment]
I will look at this issue this week.

On Mon, Nov 2, 2015 at 9:00 AM, Dane <notifications@github.com> wrote:

> Hi,
> Just wondering if anyone is working on this. If so I'll continue w/ the
> expectation that it will be fixed otherwise I'll need to work around the
> issue by copying all the tables as temporary tables to PostgreSQL. So if
> someone could let me know which way to go I would appreciate it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EnterpriseDB/mysql_fdw/issues/70#issuecomment-153083103>
> .
>



-- 
Ibrar Ahmed
EnterpriseDB   http://www.enterprisedb.com

**Comment by studdugie** [comment]
Thanks!

**Comment by studdugie** [comment]
Thanks for fixing this ibrarahmad! You've added a notch to my happy meter.
