### ISSUE TITLE
a bug when parsing subquery for empty group by

### ISSUE THREAD

**Issue by dPeS** [EnterpriseDB/mysql_fdw#74]
I got this when PG_TAB is >empty<, a bug probably

select count(*), (select name from FDW_TAB where id = xid) from PG_TAB group by xid;

ERROR:  failed to prepare the MySQL query: 
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '::integer))' at line 1

I'm using newest release

**Comment by ibrarahmad** [comment]
Please share complete test case

**Comment by dPeS** [comment]
it looks like it's working on master but not on 2.0.1, I upgraded it recently from different reason and now works ok, ticket to close imo.

**Comment by dPeS** [comment]
tested on 9cd6963ac76ba62ebb6fd5d584ec4725d0f56424 commit
