### ISSUE TITLE
Build fails on 9.5

### ISSUE THREAD

**Issue by coreyatmoat** [EnterpriseDB/mysql_fdw#76]
A seventh parameter was added to make_foreignscan() on Oct 15th:

http://git.postgresql.org/gitweb/?p=postgresql.git;a=commit;h=5043193b78919a1bd144563aadc2f7f726549913

This FDW seems to have the same issue as found here:

https://github.com/Kozea/Multicorn/issues/119

**Comment by ibrarahmad** [comment]
Fixed

**Comment by devrimgunduz** [comment]
Hi,

Any chance we can get a release RSN, which includes this fix? 9.5 is out this week, so I'd like to get new mysql_fdw out of the door.

Thanks!

**Comment by ahsanhadi** [comment]
On Tue, Jan 5, 2016 at 12:57 AM, Devrim Gündüz <notifications@github.com>
wrote:

> Hi,
>
> Any chance we can get a release RSN, which includes this fix? 9.5 is out
> this week, so I'd like to get new mysql_fdw out of the door.
>
Okay sure...We will try to release this week. We have fixed a bunch of
other issues and also committed a fix for supporting remote estimates so it
will be good to put out a release.


> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EnterpriseDB/mysql_fdw/issues/76#issuecomment-168783930>
> .
>



-- 
Ahsan Hadi
Snr Director Product Development
EnterpriseDB Corporation
The Enterprise Postgres Company

Phone: +92-51-8358874
Mobile: +92-333-5162114

Website: www.enterprisedb.com
EnterpriseDB Blog: http://blogs.enterprisedb.com/
Follow us on Twitter: http://www.twitter.com/enterprisedb

This e-mail message (and any attachment) is intended for the use of the
individual or entity to whom it is addressed. This message contains
information from EnterpriseDB Corporation that may be privileged,
confidential, or exempt from disclosure under applicable law. If you are
not the intended recipient or authorized to receive this for the intended
recipient, any use, dissemination, distribution, retention, archiving, or
copying of this communication is strictly prohibited. If you have received
this e-mail in error, please notify the sender immediately by reply e-mail
and delete this message.

**Comment by ChristophBerg** [comment]
Fwiw, Debian and apt.postgresql.org are awaiting the new version as well :)

**Comment by devrimgunduz** [comment]
Ping. This has stayed so long, I think.

**Comment by ahsanhadi** [comment]
Hi Devrim,

I didn't get a response from product management on this. In any case we
will ensure that mysql_fdw and mongo_fdw are working with 9.5 and released
on github before wed of this week.

-- Ahsan


On Mon, Jan 18, 2016 at 2:48 PM, Devrim Gündüz <notifications@github.com>
wrote:

> Ping. This has stayed so long, I think.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EnterpriseDB/mysql_fdw/issues/76#issuecomment-172480904>
> .
>



-- 
Ahsan Hadi
Snr Director Product Development
EnterpriseDB Corporation
The Enterprise Postgres Company

Phone: +92-51-8358874
Mobile: +92-333-5162114

Website: www.enterprisedb.com
EnterpriseDB Blog: http://blogs.enterprisedb.com/
Follow us on Twitter: http://www.twitter.com/enterprisedb

This e-mail message (and any attachment) is intended for the use of the
individual or entity to whom it is addressed. This message contains
information from EnterpriseDB Corporation that may be privileged,
confidential, or exempt from disclosure under applicable law. If you are
not the intended recipient or authorized to receive this for the intended
recipient, any use, dissemination, distribution, retention, archiving, or
copying of this communication is strictly prohibited. If you have received
this e-mail in error, please notify the sender immediately by reply e-mail
and delete this message.
