### ISSUE TITLE
CONTRIBUTING.md is blank and license is not an Open Source license...

### ISSUE THREAD

**Issue by InfoSec812** [EnterpriseDB/mysql_fdw#90]
I'd like to contribute more to this project, but for work purposes I need to know the license and contributing guidelines. If I can get this information, I am allowed to contribute to this project during work hours.

**Comment by dpage** [comment]
It's the PostgreSQL licence as shown in the licence file in the root of the source tree. It is recognised by the OSI as Open Source.

**Comment by InfoSec812** [comment]
OK, I just didn't recognize that as the "PostgreSQL license" because it is not referred to as such in the file. Unfortunately, that license is not currently approved for use by our legal team.. I will ask them to review and possibly approve.

Thanks!
